# Generated by Django 6.1 on 2026-08-21 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('openPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closePrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('highPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lowPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', '-date'], name='api_stockda_stock_i_208c62_idx'), models.Index(fields=['date'], name='api_stockda_date_481eae_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
