# Generated by Django 6.1 on 2026-08-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockday',
            old_name='closePrice',
            new_name='close_price',
        ),
        migrations.RenameField(
            model_name='stockday',
            old_name='highPrice',
            new_name='high_price',
        ),
        migrations.RenameField(
            model_name='stockday',
            old_name='lowPrice',
            new_name='low_price',
        ),
        migrations.RenameField(
            model_name='stockday',
            old_name='openPrice',
            new_name='open_price',
        ),
    ]
