# Generated by Django 6.1.1 on 2026-09-16 09:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_closeprice_stockday_close_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Ticker must be uppercase and at most 5 characters.', regex='^[A-Z]{1,5}$')]),
        ),
        migrations.AlterField(
            model_name='stockday',
            name='close_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='stockday',
            name='high_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='stockday',
            name='low_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='stockday',
            name='open_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='stockday',
            name='volume',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
