# Generated by Django 6.1.1 on 2026-09-16 10:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_stock_ticker_alter_stockday_close_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Ticker must be uppercase and at most 5 characters.', regex='\\A[A-Z]{1,5}\\Z')]),
        ),
        migrations.AddConstraint(
            model_name='stockday',
            constraint=models.CheckConstraint(condition=models.Q(('open_price__gte', Decimal('0.01'))), name='stockday_open_price_gte_001'),
        ),
        migrations.AddConstraint(
            model_name='stockday',
            constraint=models.CheckConstraint(condition=models.Q(('close_price__gte', Decimal('0.01'))), name='stockday_close_price_gte_001'),
        ),
        migrations.AddConstraint(
            model_name='stockday',
            constraint=models.CheckConstraint(condition=models.Q(('high_price__gte', Decimal('0.01'))), name='stockday_high_price_gte_001'),
        ),
        migrations.AddConstraint(
            model_name='stockday',
            constraint=models.CheckConstraint(condition=models.Q(('low_price__gte', Decimal('0.01'))), name='stockday_low_price_gte_001'),
        ),
        migrations.AddConstraint(
            model_name='stockday',
            constraint=models.CheckConstraint(condition=models.Q(('volume__gte', 1)), name='stockday_volume_gte_1'),
        ),
    ]
